# Comment to be posted to on first time issues
newIssueWelcomeComment: >
  Welcome! If you're reporting a bug, please make sure you have completed the bug report template see https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md#bug-report.
  Please make sure you provide enough detail that **someone else** can reproduce the issue you are experiencing. 
  
  We prefer to keep this issue track just for bug reports. If you have a question or need help with something I'd ask that you self close this issue and have a read over https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md it contains
  background information, details on where to ask your questions (hint, [Gitter](https://gitter.im/cefsharp/CefSharp) is one such place)
  
  It's also reportant to remember that `CefSharp` is just a wrapper around the `Chromium Embedded Framework(CEF)`, a lot of questions people
  have aren't actually `CefSharp` specific, they're generic to `CEF` and for those `CEF` has it's own support forum at http://magpcss.org/ceforum/index.php and issue tracker at https://bitbucket.org/chromiumembedded/cef
  
  
