version: 144.0.270-RCI{build}

clone_depth: 10

image: Visual Studio 2022

configuration: Release

build_script:
  - ps: .\build.ps1
  - ps: .\build.ps1 -TargetFramework NetCore

test_script:
  # Test our Release x64 build
  - dotnet test CefSharp.Test\bin\x64\Release\win-x64\CefSharp.Test.dll --verbosity normal
  - dotnet test CefSharp.Test\bin.netcore\x64\Release\net6.0-windows\win-x64\CefSharp.Test.dll --verbosity normal

artifacts:
  - path: NuGet\**\*.nupkg
    name: nupkgfiles

#Skip builing if we only modify text files
skip_commits:
  files:
    - '**/*.md'
    - '**/*.html'
    - '**/*.js'
    - '**/*.css'
    - '**/*.txt'
