//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CefSharp.Example.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CefSharp.Example.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        /// * Bootstrap Documentation
        /// * Special styles for presenting Bootstrap&apos;s documentation and code examples.
        /// *
        /// * Table of contents:
        /// *
        /// * Scaffolding
        /// * Main navigation
        /// * Footer
        /// * Social buttons
        /// * Homepage
        /// * Page headers
        /// * Old docs callout
        /// * Ads
        /// * Side navigation
        /// * Docs sections
        /// * Callouts
        /// * Grid styles
        /// * Examples
        /// * Code snippets (highlight)
        /// * Responsive tests
        /// * Glyphicons
        /// * Customizer
        /// * Miscellaneous
        /// */
        ///
        ///
        ////*
        /// * Scaffolding
        /// *
        /// * Update the basics of our documents to prep for docs content. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string assets_css_docs_css {
            get {
                return ResourceManager.GetString("assets_css_docs_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /**
        /// * SyntaxHighlighter
        /// * http://alexgorbatchev.com/SyntaxHighlighter
        /// *
        /// * SyntaxHighlighter is donationware. If you are using it, please donate.
        /// * http://alexgorbatchev.com/SyntaxHighlighter/donate.html
        /// *
        /// * @version
        /// * 3.0.83 (July 02 2010)
        /// * 
        /// * @copyright
        /// * Copyright (C) 2004-2010 Alex Gorbatchev.
        /// *
        /// * @license
        /// * Dual licensed under the MIT and GPL licenses.
        /// */
        ///.syntaxhighlighter a,
        ///.syntaxhighlighter div,
        ///.syntaxhighlighter code,
        ///.syntaxhighlighter table,
        ///.syntaxhighlighter table td,
        ///.syntaxh [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string assets_css_shCore_css {
            get {
                return ResourceManager.GetString("assets_css_shCore_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /**
        /// * SyntaxHighlighter
        /// * http://alexgorbatchev.com/SyntaxHighlighter
        /// *
        /// * SyntaxHighlighter is donationware. If you are using it, please donate.
        /// * http://alexgorbatchev.com/SyntaxHighlighter/donate.html
        /// *
        /// * @version
        /// * 3.0.83 (July 02 2010)
        /// * 
        /// * @copyright
        /// * Copyright (C) 2004-2010 Alex Gorbatchev.
        /// *
        /// * @license
        /// * Dual licensed under the MIT and GPL licenses.
        /// */
        ///.syntaxhighlighter a,
        ///.syntaxhighlighter div,
        ///.syntaxhighlighter code,
        ///.syntaxhighlighter table,
        ///.syntaxhighlighter table td,
        ///.syntaxh [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string assets_css_shCoreDefault_css {
            get {
                return ResourceManager.GetString("assets_css_shCoreDefault_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // NOTICE!! DO NOT USE ANY OF THIS JAVASCRIPT
        ///// IT&apos;S ALL JUST JUNK FOR OUR DOCS!
        ///// ++++++++++++++++++++++++++++++++++++++++++
        ///
        ///!function ($) {
        ///    $(function () {
        ///        var $window = $(window);
        ///        var $body = $(document.body);
        ///        var navHeight = $(&apos;.navbar&apos;).outerHeight(true) + 10;
        ///        $body.scrollspy({
        ///            target: &apos;.bs-sidebar&apos;,
        ///            offset: navHeight
        ///        });
        ///        $window.on(&apos;load&apos;, function () {
        ///            $body.scrollspy(&apos;refresh&apos;);
        ///        });
        ///        $(&apos;.bs-docs [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string assets_js_application_js {
            get {
                return ResourceManager.GetString("assets_js_application_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! jQuery v1.10.2 | (c) 2005, 2013 jQuery Foundation, Inc. | jquery.org/license
        /////@ sourceMappingURL=jquery-1.10.2.min.map
        ///*/
        ///(function(e,t){var n,r,i=typeof t,o=e.location,a=e.document,s=a.documentElement,l=e.jQuery,u=e.$,c={},p=[],f=&quot;1.10.2&quot;,d=p.concat,h=p.push,g=p.slice,m=p.indexOf,y=c.toString,v=c.hasOwnProperty,b=f.trim,x=function(e,t){return new x.fn.init(e,t,r)},w=/[+-]?(?:\d*\.|)\d+(?:[eE][+-]?\d+|)/.source,T=/\S+/g,C=/^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g,N=/^(?:\s*(&lt;[\w\W]+&gt;)[^&gt;]*|#([\w-]*))$/,k=/^ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string assets_js_jquery_js {
            get {
                return ResourceManager.GetString("assets_js_jquery_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /**
        /// * SyntaxHighlighter
        /// * http://alexgorbatchev.com/SyntaxHighlighter
        /// *
        /// * SyntaxHighlighter is donationware. If you are using it, please donate.
        /// * http://alexgorbatchev.com/SyntaxHighlighter/donate.html
        /// *
        /// * @version
        /// * 3.0.83 (July 02 2010)
        /// * 
        /// * @copyright
        /// * Copyright (C) 2004-2010 Alex Gorbatchev.
        /// *
        /// * @license
        /// * Dual licensed under the MIT and GPL licenses.
        /// */
        ///;(function()
        ///{
        ///	// CommonJS
        ///	typeof(require) != &apos;undefined&apos; ? SyntaxHighlighter = require(&apos;shCore&apos;).SyntaxHighlighter : null;
        ///
        ///	functi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string assets_js_shBrushCSharp_js {
            get {
                return ResourceManager.GetString("assets_js_shBrushCSharp_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /**
        /// * SyntaxHighlighter
        /// * http://alexgorbatchev.com/SyntaxHighlighter
        /// *
        /// * SyntaxHighlighter is donationware. If you are using it, please donate.
        /// * http://alexgorbatchev.com/SyntaxHighlighter/donate.html
        /// *
        /// * @version
        /// * 3.0.83 (July 02 2010)
        /// * 
        /// * @copyright
        /// * Copyright (C) 2004-2010 Alex Gorbatchev.
        /// *
        /// * @license
        /// * Dual licensed under the MIT and GPL licenses.
        /// */
        ///eval(function (p, a, c, k, e, d) { e = function (c) { return (c &lt; a ? &apos;&apos; : e(parseInt(c / a))) + ((c = c % a) &gt; 35 ? String.fromCharCo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string assets_js_shCore_js {
            get {
                return ResourceManager.GetString("assets_js_shCore_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///    &lt;head&gt;
        ///        &lt;title&gt;Binding Test&lt;/title&gt;
        ///    &lt;/head&gt;
        ///    &lt;body&gt;
        ///        &lt;p&gt;
        ///        Result of calling bound.repeat(&quot;hi &quot;, 5) =
        ///        &lt;script type=&quot;text/javascript&quot;&gt;
        ///            var result = bound.repeat(&quot;hi &quot;, 5);
        ///            document.write(&apos;&quot;&apos; + result + &apos;&quot;&apos;);
        ///            if(result == &quot;hi hi hi hi hi &quot;)
        ///            {
        ///                document.write(&quot; SUCCESS&quot;);
        ///            }
        ///            else
        ///            {
        ///                document. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BindingTest {
            get {
                return ResourceManager.GetString("BindingTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * Bootstrap v3.0.0
        /// *
        /// * Copyright 2013 Twitter, Inc
        /// * Licensed under the Apache License v2.0
        /// * http://www.apache.org/licenses/LICENSE-2.0
        /// *
        /// * Designed and built with all the love in the world by @mdo and @fat.
        /// *//*! normalize.css v2.1.0 | MIT License | git.io/normalize */article,aside,details,figcaption,figure,footer,header,hgroup,main,nav,section,summary{display:block}audio,canvas,video{display:inline-block}audio:not([controls]){display:none;height:0}[hidden]{display:none}html{font-family:sans-s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bootstrap_min_css {
            get {
                return ResourceManager.GetString("bootstrap_min_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /**
        ///* bootstrap.js v3.0.0 by @fat and @mdo
        ///* Copyright 2013 Twitter Inc.
        ///* http://www.apache.org/licenses/LICENSE-2.0
        ///*/
        ///if (!jQuery) throw new Error(&quot;Bootstrap requires jQuery&quot;); +function (a) { &quot;use strict&quot;; function b() { var a = document.createElement(&quot;bootstrap&quot;), b = { WebkitTransition: &quot;webkitTransitionEnd&quot;, MozTransition: &quot;transitionend&quot;, OTransition: &quot;oTransitionEnd otransitionend&quot;, transition: &quot;transitionend&quot; }; for (var c in b) if (void 0 !== a.style[c]) return { end: b[c] } } a.fn.emulateTransit [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bootstrap_min_js {
            get {
                return ResourceManager.GetString("bootstrap_min_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .btn-default,.btn-primary,.btn-success,.btn-info,.btn-warning,.btn-danger{text-shadow:0 -1px 0 rgba(0,0,0,0.2);-webkit-box-shadow:inset 0 1px 0 rgba(255,255,255,0.15),0 1px 1px rgba(0,0,0,0.075);box-shadow:inset 0 1px 0 rgba(255,255,255,0.15),0 1px 1px rgba(0,0,0,0.075)}.btn-default:active,.btn-primary:active,.btn-success:active,.btn-info:active,.btn-warning:active,.btn-danger:active,.btn-default.active,.btn-primary.active,.btn-success.active,.btn-info.active,.btn-warning.active,.btn-danger.active{-webkit-b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bootstrap_theme_min_css {
            get {
                return ResourceManager.GetString("bootstrap_theme_min_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;!-- Meta, title, CSS, favicons, etc. --&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///    &lt;meta name=&quot;description&quot; content=&quot;&quot;&gt;
        ///    &lt;meta name=&quot;author&quot; content=&quot;&quot;&gt;
        ///    &lt;title&gt;Getting started &amp;middot; CefSharp &lt;/title&gt;
        ///    &lt;!-- Bootstrap core CSS --&gt;
        ///    &lt;link href=&quot;bootstrap/bootstrap.min.css&quot; rel=&quot;stylesheet&quot;&gt;
        ///    &lt;!-- Page-specific extras --&gt;
        ///    &lt;link href=&quot;assets/css/docs.css&quot; rel=&quot;stylesheet&quot;&gt;
        ///    &lt;link [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string home_html {
            get {
                return ResourceManager.GetString("home_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;Popup Test&lt;/title&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///        &lt;a href=&quot;https://github.com/perlun/CefSharp&quot; target=&quot;_blank&quot;&gt;target=_blank&lt;/a&gt;
        ///        &lt;br /&gt;
        ///        &lt;a href=&quot;#&quot; onclick=&quot;window.open(&apos;https://github.com/perlun/CefSharp&apos;)&quot;&gt;window.open()&lt;/a&gt;
        ///	&lt;/body&gt;
        ///&lt;/html&gt;
        ///.
        /// </summary>
        internal static string PopupTest {
            get {
                return ResourceManager.GetString("PopupTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;Scheme Handler Test&lt;/title&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///	&lt;h1&gt;Success&lt;/h1&gt;
        ///	&lt;p&gt;Scheme Handler Functioned Correctly&lt;/p&gt;
        ///	&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string SchemeTest {
            get {
                return ResourceManager.GetString("SchemeTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;Scheme Handler Test&lt;/title&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///        &lt;form&gt;
        ///            &lt;input type=&quot;text&quot; size=25 title=&quot;This is the first tooltip&quot;&gt;
        ///            &lt;br /&gt;
        ///            &lt;input type=&quot;text&quot; size=25 title=&quot;This is the second tooltip&quot;&gt;
        ///            &lt;br /&gt;
        ///            &lt;select&gt;
        ///                &lt;option selected&gt;test&lt;/option&gt;
        ///                &lt;option&gt;one&lt;/option&gt;
        ///                &lt;option&gt;two&lt;/option&gt;
        ///            &lt;/select&gt;
        ///        &lt;/form [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TooltipTest {
            get {
                return ResourceManager.GetString("TooltipTest", resourceCulture);
            }
        }
    }
}
